RAS 926: Update Flask in Reporting and sort out vulnerabilities (main ticket)
ONSdigital/sdc-responses-dashboard pull request #148
Opened 2023-12-15 09:04 UTC by SteveScorfield

# What and why?
The structlog.threadlocal was found to be deprecated. This ticket deals with removing this.

# How to test?
Run unit tests, acceptance tests and check in your dev env

# Jira
https://jira.ons.gov.uk/browse/RAS-926
https://jira.ons.gov.uk/browse/RAS-964

2023-12-15 09:15 UTC, SteveScorfield commented
/deploy scorfs

2023-12-15 10:25 UTC, SteveScorfield commented
/deploy scorfs

2023-12-19 12:35 UTC, LJBabbage requested changes
Think this one should be a separate story, it's also not updating to Flask 3

2023-12-19 12:35 UTC, LJBabbage commented on app/setup.py
> +        context_class=dict,
Probably one for a different story, this is the old way of using structlog and isn't thread save. I have no idea what removing the wrap will do in regards to how the logs look, however I also think if we touching this we should do it properly. Should be like this now https://github.com/ONSdigital/ras-frontstage/pull/918/files

2023-12-19 14:26 UTC, anwilkie commented
/deploy wilkia

2023-12-19 15:21 UTC, SteveScorfield commented
Not needed for this ticket

2023-12-19 15:21 UTC, closed without merging