pipenv update
ONSdigital/sdc-responses-dashboard pull request #159
Opened 2024-05-17 09:48 UTC by anwilkie

# What and why?
This PR resolves a bunch of dependabot alerts. There were a ton, so it felt best to do them as one PR.

# How to test?
TBD

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-1161)

2024-05-20 11:17 UTC, LJBabbage requested changes
Some of these dependencies are connected to selenium and smoke tests, which currently don't seem to work or are on the build/test path. The smoke tests don't seem to work for me, so I can't confirm if the updates work unfortunately

2024-05-20 13:44 UTC, matthew-robinson-ons reviewed
Also experiencing the same issue as Lewis. Unsure of the changes in the package-lock.json, specifically why [lockfileVersion](https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json#lockfileversion) is being updated from 3 to 1, and a lot dependencies getting removed.

2024-05-22 13:40 UTC, matthew-robinson-ons approved these changes
Happy with the new version of the package-lock.json and rest of the changes seem appropriate, all packages updated listed updated.

2024-05-22 14:56 UTC, LJBabbage approved these changes

2024-05-23 08:17 UTC, merged