adding ignore
ONSdigital/sdc-responses-dashboard pull request #174
Opened 2024-10-18 15:57 UTC by anwilkie

# What and why?
This PR updates the dependencies and adds an ignore to the makefile.

# How to test?
Deploy and run tests.

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-1315)

2024-10-18 16:32 UTC, anwilkie commented
/deploy wilkia

2024-10-21 10:38 UTC, arroyoAle requested changes
While they look fine we shouldn't just update all the dependencies like this, we don't really know whats coming through so if anything breaks it'll be lost - I think the card was more looking at progressing any security dependencies rather than a general update. For this repo specifically we have another card to progress the security updates

2024-10-23 09:43 UTC, matthew-robinson-ons approved these changes
Changes look appropriate and given there is a card for the dependabot alerts, looks good

2024-10-25 09:10 UTC, arroyoAle approved these changes

2024-10-25 12:29 UTC, merged