Select collection exercise based on survey
ONSdigital/sdc-responses-dashboard pull request #22
Opened 2018-07-06 08:41 UTC by MebinAbraham

### What is the context of this PR?
Show collection exercise based on the chosen survey.
Only displays surveys with at least one collection exercise.

### How to review 
Ensure:
- app works as expected.
- surveys are only shown with collection exercises.
- selecting a collection exercise displays details for chosen exercise.

2018-07-06 08:42 UTC, ryangrundy7 submitted a review, later dismissed

2018-07-06 08:42 UTC, ryangrundy7 commented on app/common/jinja_filters.py
> +
Don't need it

2018-07-06 10:40 UTC, AdamHawtin requested changes

2018-07-06 10:40 UTC, AdamHawtin commented on app/static/assets/js/dashboard.js
> +            "title": "Collecton Exercise Period",
Spelling mistake

2018-07-06 10:48 UTC, ryangrundy7 requested changes
Refreshing a page turns into an empty page

2018-07-06 13:21 UTC, AdamHawtin approved these changes

2018-07-06 13:26 UTC, ryangrundy7 approved these changes

2018-07-06 13:42 UTC, merged

2018-07-13 10:32 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Selecting the exercise once in a survey](https://trello.com/c/ItzBKaCm/33-selecting-the-exercise-once-in-a-survey)