Remove different behaviour for listed SEFT surveys
ONSdigital/sdc-responses-dashboard pull request #57
Opened 2018-11-30 14:13 UTC by AdamHawtin

# Motivation and Context
We cannot currently reliably tell which collection exercises are SEFT versus EQ, the solution we had with a hardcoded list is not sustainable and needs to be removed. This PR removes all different behaviours for SEFT and removes the hardcoded list of ID's. The dashboard now treats all collection exercises the same.

# What has changed
- Removed list of SEFT survey ID's
- Removed all different behaviour for SEFT collection exercises

# How to test?
Run the dashboard, open a SEFT collection exercise. It should now show the same figures as the EQ dashboards.

2018-12-04 16:42 UTC, MebinAbraham commented on app/static/assets/js/reporting.js
> +    report = getReport(response);
Can now be:
``` js
let report = getReport(response)
```

2018-12-04 16:43 UTC, MebinAbraham reviewed
Apart from the 1 minor comment, looks good.

2018-12-04 16:59 UTC, ryangrundy7 requested changes
Collection instrument type is still on some of the tests which is causing the test coverage to get worse.

2018-12-04 16:59 UTC, ryangrundy7 commented on tests/app/api/test_reporting.py
>          response = self.test_client.get('/dashboard/reporting/eq'
Collection instrument type is still on this test. It's not hitting anything in the repo

2018-12-06 10:31 UTC, ryangrundy7 approved these changes

2018-12-07 09:01 UTC, MebinAbraham commented on scripts/mock_services.py
> +    accounts_pending = rand_gen.randint(0, (sample_size - accounts_enrolled)//10)
Can you format to `(sample_size - accounts_enrolled) // 10)`, standard style.

2018-12-07 09:04 UTC, MebinAbraham approved these changes

2018-12-07 14:18 UTC, merged