Add tooltips for dashboard figures
ONSdigital/sdc-responses-dashboard pull request #61
Opened 2018-12-14 14:10 UTC by ryangrundy7

# Motivation and Context
There's no way to show the difference between a SEFT or eQ collection exercise so we've added a tooltip to describe what each figure represents.

# What has changed
- Added tooltip

# How to test?
- Run dashboard and see if tooltip appears over figures

# Links
[Trello](https://trello.com/c/o1EIjnBt)

2018-12-14 14:47 UTC, MebinAbraham approved these changes

2018-12-14 14:48 UTC, AdamHawtin approved these changes

2018-12-14 14:49 UTC, AdamHawtin requested changes
The number

2018-12-14 15:02 UTC, AdamHawtin approved these changes

2018-12-14 15:03 UTC, merged

2018-12-19 09:15 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add a tooltip to the dashboard figures](https://trello.com/c/o1EIjnBt/97-add-a-tooltip-to-the-dashboard-figures)