Use execution/go live date for start date in CE selection modal
ONSdigital/sdc-responses-dashboard pull request #64
Opened 2019-01-04 10:33 UTC by AdamHawtin

### Motivation and Context
Changes the start date in the collection exercise selection modal to use the execution (go live) date as this is representative of the actual survey start date. Previously it was using the period start date which is a reference date for the questions, not the actual survey execution.

### What has changed
- Change the survey metadata helper functions to use execution date
- Change the modal javascript to use the execution date
- Update unit tests
- Update static assets version

### How to test?
Run the service locally, the collection exercise selection menu should now show the go live date not the period start date

### Links
https://trello.com/c/Zmpzyepx/102-use-go-live-date-for-start-date-on-the-collection-exercise-selection-modal

### Checklist

* [ ] STATIC_ASSETS_VERSION updated.

2019-01-04 10:34 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use "Go Live" date for start date on the collection exercise selection modal](https://trello.com/c/Zmpzyepx/102-use-go-live-date-for-start-date-on-the-collection-exercise-selection-modal)

2019-01-25 09:06 UTC, MebinAbraham requested changes
Just one thing, but working as expected.

2019-01-25 09:06 UTC, MebinAbraham commented on tests/app/test_survey_metadata.py
> +            '14fb3e68-4dca-46db-bf49-04b84e07e777': {'exerciseRef': '201812',
Can we keep the formmating consistent.
```python
{
    '14fb3e68-4dca-46db-bf49-04b84e07e777': {
        'exerciseRef': '201812',
        'longName': 'Quarterly Business Survey',
        'scheduledExecutionDateTime': '2017-09-10T23:00:00.000Z',
        'scheduledReturnDateTime': '2017-10-06T00:00:00.000Z',
        'shortName': 'QBS',
        'surveyId': '04dbb407-4438-4f89-acc4-53445d753111',
        'surveyType': 'Business',
        'userDescription': 'Quarterly Business Survey'
    },
    '14fb3e68-4dca-46db-bf49-04b84e07e77c': {
        'exerciseRef': '201712',
        'longName': 'Business Register and Employment Survey',
        'scheduledExecutionDateTime': '2017-09-10T23:00:00.000Z',
        'scheduledReturnDateTime': '2017-10-06T00:00:00.000Z',
        'shortName': 'BRES',
        'surveyId': 'cb0711c3-0ac8-41d3-ae0e-567e5ea1ef87',
        'surveyType': 'Business',
        'userDescription': 'December 2017'
    },
    '24fb3e68-4dca-46db-bf49-04b84e07e77c': {
        'exerciseRef': '201801',
        'longName': 'Business Register and Employment Survey',
        'scheduledExecutionDateTime': '2017-09-10T23:00:00.000Z',
        'scheduledReturnDateTime': '2017-10-06T00:00:00.000Z',
        'shortName': 'BRES',
        'surveyId': 'cb0711c3-0ac8-41d3-ae0e-567e5ea1ef87',
        'surveyType': 'Business',
        'userDescription': 'January 2018'
    }
}
```

2019-01-25 13:42 UTC, ryangrundy7 approved these changes

2019-02-01 09:22 UTC, MebinAbraham approved these changes

2019-02-01 14:52 UTC, merged