Adding docker files
ONSdigital/sdc-responses-dashboard pull request #65
Opened 2019-01-15 15:48 UTC by ryangrundy7

### Motivation and Context
Creating a docker image allows us to easily bring up our project with the other services it needs to run with.
### What has changed
- Added Dockerfile and docker-compose.yml file

### How to test?
- As the docker image isn't on dockerhub yet, you'll have to build it using `docker build -t sdc-responses-dashboard .`. Once the image has been built, you should be able to bring up the service using `docker-compose up -d`.

### Links
[Trello](https://trello.com/c/AvSfWzbk)

### Checklist

* [ ] STATIC_ASSETS_VERSION updated.

2019-01-16 08:55 UTC, AdamHawtin requested changes

2019-01-16 08:55 UTC, AdamHawtin commented on README.md
> +docker build -t sdcplatform/sdc-responses-dashboard .
Either this or the `image` line in the compose yaml should be changed to match, the `docker-compose up` fails if the image names don't match.

2019-01-16 09:18 UTC, ryangrundy7 commented on README.md
> +docker build -t sdcplatform/sdc-responses-dashboard .
Yeah you're right, I think if we put it on the sdcplatform images then it'll be the one above

2019-01-25 15:32 UTC, MebinAbraham approved these changes

2019-01-28 08:57 UTC, AdamHawtin approved these changes

2019-02-08 12:16 UTC, merged